INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_1',
        '1',
        'Rollitos vegetales',
        'ENTRANTE',
        'Rollitos rellenos ...',
        NULL,
        3.5,
        '["Gluten","Pescado","Lácteos"]',
        'verified',
        'https://oyishi.es/public/uploadfile/677fe50065be6.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=1',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_9',
        '1A',
        'Minirollitos',
        'ENTRANTE',
        '(10 unidades)',
        10,
        3,
        '["Gluten"]',
        'verified',
        'https://oyishi.es/public/uploadfile/20260525153533856267.jpg',
        'official',
        'https://oyishi.es/menu_detail.php?id=9',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_2',
        '2',
        'Rollitos de gambas',
        'ENTRANTE',
        'Rellenos de gamba ...',
        NULL,
        4.5,
        '["Gluten","Crustáceos","Cacahuetes"]',
        'verified',
        'https://oyishi.es/public/uploadfile/677fe500664a1.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=2',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_162',
        '2A',
        'Langostino tempura estilo japonesa',
        'ENTRANTE',
        '(4 unidades)',
        4,
        5.95,
        '["Gluten","Crustáceos","Cacahuetes"]',
        'verified',
        'https://oyishi.es/public/uploadfile/20260525153656236865.jpg',
        'official',
        'https://oyishi.es/menu_detail.php?id=162',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_3',
        '3',
        'Rollitos de queso',
        'ENTRANTE',
        'Rellenos de queso ...',
        NULL,
        3.5,
        '["Gluten","Huevos","Cacahuetes"]',
        'verified',
        'https://oyishi.es/public/uploadfile/677fe500669aa.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=3',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_4',
        '4',
        'Gyozas de carne y verduras',
        'ENTRANTE',
        'Empanadillas a la ...',
        NULL,
        5.8,
        '["Gluten","Pescado","Lácteos"]',
        'verified',
        'https://oyishi.es/public/uploadfile/677fe50066d88.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=4',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_5',
        '5',
        'Shumai',
        'ENTRANTE',
        '(masa transparent ...',
        NULL,
        4.5,
        '["Gluten","Pescado"]',
        'verified',
        'https://oyishi.es/public/uploadfile/677fe50067068.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=5',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_6',
        '6',
        'Jiaozi de gambas',
        'ENTRANTE',
        '(masa de almidon d...',
        NULL,
        5,
        '["Gluten","Crustáceos"]',
        'verified',
        'https://oyishi.es/public/uploadfile/677fe500674b0.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=6',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_7',
        '7',
        'Jiaozi peonies',
        'ENTRANTE',
        '(Came se cerdo cam...',
        NULL,
        4.9,
        '["Gluten","Crustáceos"]',
        'verified',
        'https://oyishi.es/public/uploadfile/677fe50067927.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=7',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_158',
        '8',
        'Gyozas vegetarianas',
        'ENTRANTE',
        NULL,
        NULL,
        5.5,
        '["Gluten","Pescado"]',
        'verified',
        'https://oyishi.es/public/uploadfile/20260525155046804089.jpg',
        'official',
        'https://oyishi.es/menu_detail.php?id=158',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_10',
        '10',
        'Xiao long bao',
        'ENTRANTE',
        '(con un relleno ju...',
        NULL,
        5,
        '["Gluten"]',
        'verified',
        'https://oyishi.es/public/uploadfile/677fe50067db1.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=10',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_11',
        '11',
        'Dim-sum variado',
        'ENTRANTE',
        '(5 piezas)',
        5,
        5.5,
        '["Gluten","Huevos","Pescado","Soja"]',
        'verified',
        'https://oyishi.es/public/images/novedad.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=11',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_12',
        '12',
        'Ensalada de algas',
        'ENTRANTE',
        '( algas pepino agu...',
        NULL,
        4,
        '["Crustáceos","Pescado","Sésamo"]',
        'verified',
        'https://oyishi.es/public/uploadfile/677fe508d169e.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=12',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_13',
        '13',
        'Goma wakame',
        'ENTRANTE',
        '(algas finas)',
        NULL,
        4,
        '["Sésamo"]',
        'verified',
        'https://oyishi.es/public/uploadfile/677fe508d1daa.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=13',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_14',
        '14',
        'Ensalada sesar',
        'ENTRANTE',
        '(Lechuga,tomate,za...',
        NULL,
        8.5,
        '["Gluten","Cacahuetes"]',
        'verified',
        'https://oyishi.es/public/uploadfile/677fe508d2211.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=14',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_15',
        '15',
        'Ensalada aguacate',
        'ENTRANTE',
        '( aguacate pepino ...',
        NULL,
        9,
        '[]',
        'unknown',
        'https://oyishi.es/public/uploadfile/677fe508d26e2.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=15',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_16',
        '16',
        'Edamame',
        'ENTRANTE',
        '(habas al vapor)',
        NULL,
        4.5,
        '[]',
        'unknown',
        'https://oyishi.es/public/uploadfile/677fe508d2b8a.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=16',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_17',
        '17',
        'Sopa miso',
        'ENTRANTE',
        NULL,
        NULL,
        2.9,
        '["Crustáceos","Pescado"]',
        'verified',
        'https://oyishi.es/public/uploadfile/677fe508d2f1b.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=17',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_160',
        '6',
        'MENÚ PARA 2 PERSONAS',
        'MENÚS',
        '4 Maki salmón4 Ma...',
        NULL,
        32.95,
        '["Frutos de cáscara"]',
        'verified',
        'https://oyishi.es/public/uploadfile/20250109163803978373.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=160',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_161',
        '4',
        'MENU PARA 4 PERSONAS',
        'MENÚS',
        '4 Rollitos4 Xiao L...',
        NULL,
        48,
        '["Pescado"]',
        'verified',
        'https://oyishi.es/public/uploadfile/20250109163810488373.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=161',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_18',
        '18',
        'California roll',
        'ROLL(8piezas)',
        '(gambas, pepino y ...',
        NULL,
        6.95,
        '["Frutos de cáscara"]',
        'verified',
        'https://oyishi.es/public/uploadfile/677fe508d324d.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=18',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_19',
        '19',
        'California salmón roll',
        'ROLL(8piezas)',
        '(salmón, pepino y...',
        NULL,
        7.85,
        '["Frutos de cáscara"]',
        'verified',
        'https://oyishi.es/public/uploadfile/677fe508d34d0.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=19',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_163',
        '19A',
        'Sésamo salmón roll',
        'ROLL(8piezas)',
        '(Salmón, pepino y...',
        NULL,
        7.5,
        '["Frutos de cáscara","Sésamo"]',
        'verified',
        'https://oyishi.es/public/uploadfile/20260525155338128270.jpg',
        'official',
        'https://oyishi.es/menu_detail.php?id=163',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_20',
        '20',
        'California Atún roll',
        'ROLL(8piezas)',
        '(atún pepino y ag...',
        NULL,
        8.45,
        '["Frutos de cáscara"]',
        'verified',
        'https://oyishi.es/public/uploadfile/677fe508d37c9.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=20',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_21',
        '21',
        'Gambas roll',
        'ROLL(8piezas)',
        '(gambas,pepino y a...',
        NULL,
        6.5,
        '["Crustáceos","Sésamo"]',
        'verified',
        'https://oyishi.es/public/uploadfile/677fe510e2538.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=21',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_22',
        '22',
        'Maki Almendra',
        'ROLL(8piezas)',
        '(salmón, aguacate...',
        NULL,
        8.5,
        '["Cacahuetes","Soja"]',
        'verified',
        'https://oyishi.es/public/uploadfile/20260525155443669451.jpg',
        'official',
        'https://oyishi.es/menu_detail.php?id=22',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_23',
        '23',
        'Sésamo roll',
        'ROLL(8piezas)',
        '(surimi, pepino y ...',
        NULL,
        6,
        '["Crustáceos","Sésamo"]',
        'verified',
        'https://oyishi.es/public/uploadfile/677fe510e2e2c.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=23',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_24',
        '24',
        'Maki dragón',
        'ROLL(8piezas)',
        '( Langostinos en t...',
        NULL,
        6.95,
        '["Crustáceos"]',
        'verified',
        'https://oyishi.es/public/uploadfile/677fe510e31d0.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=24',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_25',
        '25',
        'Spicy salmon crunch',
        'ROLL(8piezas)',
        '(salmón, aguacate...',
        NULL,
        7.95,
        '["Gluten","Cacahuetes","Frutos de cáscara","Sésamo"]',
        'verified',
        'https://oyishi.es/public/uploadfile/677fe510e3553.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=25',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_26',
        '26',
        'Spicy tuna crunch',
        'ROLL(8piezas)',
        '(atún, aguante, m...',
        NULL,
        7.95,
        '["Gluten","Pescado","Cacahuetes","Frutos de cáscara"]',
        'verified',
        'https://oyishi.es/public/uploadfile/677fe510e3895.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=26',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_27',
        '27',
        'Spicy gamba crunch',
        'ROLL(8piezas)',
        '(gambas, aguante, ...',
        NULL,
        7.5,
        '["Gluten","Crustáceos","Pescado","Cacahuetes"]',
        'verified',
        'https://oyishi.es/public/images/novedad.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=27',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_28',
        '28',
        'Aguacate uramaki',
        'URAMAKI(8piezas)',
        '(gambas, aguacate,...',
        NULL,
        8.5,
        '["Crustáceos","Cacahuetes"]',
        'verified',
        'https://oyishi.es/public/uploadfile/677fe510e3e39.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=28',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_164',
        '28A',
        'Uramaki mango',
        'URAMAKI(8piezas)',
        '(Salmón, aguacate...',
        NULL,
        8.9,
        '["Cacahuetes","Frutos de cáscara"]',
        'verified',
        'https://oyishi.es/public/uploadfile/20260525155913617818.jpg',
        'official',
        'https://oyishi.es/menu_detail.php?id=164',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_29',
        '29',
        'Cheese bamboo roll',
        'URAMAKI(8piezas)',
        '(aguacate y queso ...',
        NULL,
        6.75,
        '["Cacahuetes"]',
        'verified',
        'https://oyishi.es/public/uploadfile/677fe510e4120.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=29',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_30',
        '30',
        'Sake cheese bamboo roll',
        'URAMAKI(8piezas)',
        '(salmón, queso Ph...',
        NULL,
        8.5,
        '["Cacahuetes","Frutos de cáscara"]',
        'verified',
        'https://oyishi.es/public/uploadfile/677fe51aa7f19.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=30',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_31',
        '31',
        'Dinamita roll',
        'URAMAKI(8piezas)',
        '(gambas, queso Phi...',
        NULL,
        8.9,
        '["Crustáceos","Cacahuetes","Frutos de cáscara"]',
        'verified',
        'https://oyishi.es/public/uploadfile/677fe51aa8486.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=31',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_32',
        '32',
        'Salmón uramaki',
        'URAMAKI(8piezas)',
        '(salmón, queso Ph...',
        NULL,
        8.9,
        '["Cacahuetes","Frutos de cáscara"]',
        'verified',
        'https://oyishi.es/public/uploadfile/677fe51aa886e.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=32',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_33',
        '33',
        'Atún uramaki',
        'URAMAKI(8piezas)',
        '(atún, queso Phil...',
        NULL,
        8.9,
        '["Cacahuetes","Frutos de cáscara"]',
        'verified',
        'https://oyishi.es/public/images/novedad.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=33',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_34',
        '34',
        'Rock roll',
        'TEMPURIZADOS(8 piezas)',
        '(pepino, aguacate,...',
        NULL,
        8.5,
        '["Gluten","Crustáceos","Pescado"]',
        'verified',
        'https://oyishi.es/public/uploadfile/677fe51aa8fb2.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=34',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_35',
        '35',
        'Maki crispy salmón',
        'TEMPURIZADOS(8 piezas)',
        '(salmón y salsa c...',
        NULL,
        9,
        '["Gluten","Pescado","Frutos de cáscara"]',
        'verified',
        'https://oyishi.es/public/uploadfile/677fe51aa9369.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=35',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_165',
        '35A',
        'Tempurizados maki de pez mantequilla',
        'TEMPURIZADOS(8 piezas)',
        '(cebolla crujiente...',
        NULL,
        9,
        '["Gluten","Pescado","Frutos de cáscara"]',
        'verified',
        'https://oyishi.es/public/uploadfile/20260525160328396791.jpg',
        'official',
        'https://oyishi.es/menu_detail.php?id=165',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_36',
        '36',
        'Maki crispy pato',
        'TEMPURIZADOS(8 piezas)',
        '(pato y salsa, ceb...',
        NULL,
        8.5,
        '["Gluten","Pescado"]',
        'verified',
        'https://oyishi.es/public/images/novedad.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=36',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_37',
        '37',
        'Sésamo roll en crispy',
        'TEMPURIZADOS(8 piezas)',
        '(pepino, aguacate,...',
        NULL,
        8,
        '["Gluten","Crustáceos","Pescado"]',
        'verified',
        'https://oyishi.es/public/uploadfile/677fe51aa993a.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=37',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_38',
        '38',
        'Sushi atun',
        'NIGIRI SUSHI(2 piezas)',
        '(Arroz y atún)',
        NULL,
        3.9,
        '["Frutos de cáscara"]',
        'verified',
        'https://oyishi.es/public/uploadfile/677fe51aa9c90.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=38',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_166',
        '38A',
        'Sushi atún flameado',
        'NIGIRI SUSHI(2 piezas)',
        NULL,
        NULL,
        4.5,
        '["Pescado","Frutos de cáscara"]',
        'verified',
        'https://oyishi.es/public/uploadfile/20260525160545797372.jpg',
        'official',
        'https://oyishi.es/menu_detail.php?id=166',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_39',
        '39',
        'Sushi salmon',
        'NIGIRI SUSHI(2 piezas)',
        '(Arroz y salmón)',
        NULL,
        3.5,
        '["Frutos de cáscara"]',
        'verified',
        'https://oyishi.es/public/uploadfile/677fe5291553d.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=39',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_167',
        '39A',
        'Sushi salmón flameado',
        'NIGIRI SUSHI(2 piezas)',
        NULL,
        NULL,
        4,
        '["Pescado","Frutos de cáscara"]',
        'verified',
        'https://oyishi.es/public/uploadfile/20260525160808935822.jpg',
        'official',
        'https://oyishi.es/menu_detail.php?id=167',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_40',
        '40',
        'Sushi gambas',
        'NIGIRI SUSHI(2 piezas)',
        'Arroz y gambas',
        NULL,
        3,
        '["Crustáceos"]',
        'verified',
        'https://oyishi.es/public/uploadfile/677fe52915873.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=40',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_41',
        '41',
        'Sushi lubina',
        'NIGIRI SUSHI(2 piezas)',
        'Arroz y lubina',
        NULL,
        4,
        '["Frutos de cáscara"]',
        'verified',
        'https://oyishi.es/public/uploadfile/677fe52915b57.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=41',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_168',
        '41A',
        'Sushi lubina flameado',
        'NIGIRI SUSHI(2 piezas)',
        NULL,
        NULL,
        4,
        '["Pescado","Frutos de cáscara"]',
        'verified',
        'https://oyishi.es/public/uploadfile/20260525161845618642.jpg',
        'official',
        'https://oyishi.es/menu_detail.php?id=168',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_169',
        '41B',
        'Sushi de vieira',
        'NIGIRI SUSHI(2 piezas)',
        NULL,
        NULL,
        3.9,
        '["Pescado","Frutos de cáscara"]',
        'verified',
        'https://oyishi.es/public/uploadfile/20260525161954608808.jpg',
        'official',
        'https://oyishi.es/menu_detail.php?id=169',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_42',
        '42',
        'Sushi Anguila',
        'NIGIRI SUSHI(2 piezas)',
        'Arroz y anguila',
        NULL,
        4,
        '["Pescado","Frutos de cáscara"]',
        'verified',
        'https://oyishi.es/public/uploadfile/677fe52915e18.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=42',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_43',
        '43',
        'Pez mantequilla',
        'NIGIRI SUSHI(2 piezas)',
        '(arroz y pez mante...',
        NULL,
        3.5,
        '["Frutos de cáscara"]',
        'verified',
        'https://oyishi.es/public/uploadfile/677fe52916058.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=43',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_170',
        '43A',
        'Sushi pez mantequill  flameado',
        'NIGIRI SUSHI(2 piezas)',
        NULL,
        NULL,
        4,
        '["Pescado","Frutos de cáscara"]',
        'verified',
        'https://oyishi.es/public/uploadfile/20260525162210390395.jpg',
        'official',
        'https://oyishi.es/menu_detail.php?id=170',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_44',
        '44',
        'Sushi aguacate',
        'NIGIRI SUSHI(2 piezas)',
        'Arroz aguante y qu...',
        NULL,
        2.8,
        '["Cacahuetes"]',
        'verified',
        'https://oyishi.es/public/uploadfile/677fe52916374.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=44',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_45',
        '45',
        'Sushi pulpo',
        'NIGIRI SUSHI(2 piezas)',
        'arroz y pulpo',
        NULL,
        4,
        '["Moluscos"]',
        'verified',
        'https://oyishi.es/public/uploadfile/677fe52916787.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=45',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_46',
        '46',
        'Sushi tobiko',
        'NIGIRI SUSHI(2 piezas)',
        'Arroz y huevas de ...',
        NULL,
        4,
        '["Frutos de cáscara"]',
        'verified',
        'https://oyishi.es/public/uploadfile/677fe52916ae1.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=46',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_47',
        '47',
        'Sushi ikura',
        'NIGIRI SUSHI(2 piezas)',
        'Arroz y huevas de ...',
        NULL,
        6,
        '["Frutos de cáscara"]',
        'verified',
        'https://oyishi.es/public/uploadfile/677fe54462b24.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=47',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_48',
        '48',
        'Sushi tartar atún',
        'NIGIRI SUSHI(2 piezas)',
        'Arroz y atún',
        NULL,
        6.5,
        '["Frutos de cáscara"]',
        'verified',
        'https://oyishi.es/public/uploadfile/677fe544630bd.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=48',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_49',
        '49',
        'Sushi tartar salmón',
        'NIGIRI SUSHI(2 piezas)',
        'Arroz y salmón',
        NULL,
        5.9,
        '["Frutos de cáscara"]',
        'verified',
        'https://oyishi.es/public/uploadfile/677fe54463448.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=49',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_50',
        '50',
        'Maki atún',
        'MAKI(8piezas)',
        'Arroz y atún',
        NULL,
        4.9,
        '["Frutos de cáscara"]',
        'verified',
        'https://oyishi.es/public/uploadfile/677fe544637d0.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=50',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_51',
        '51',
        'Maki salmón',
        'MAKI(8piezas)',
        '(arroz y salmón)',
        NULL,
        4.5,
        '["Frutos de cáscara"]',
        'verified',
        'https://oyishi.es/public/uploadfile/677fe54463b26.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=51',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_52',
        '52',
        'Maki anguila',
        'MAKI(8piezas)',
        '(arroz y anguila)',
        NULL,
        6,
        '["Frutos de cáscara"]',
        'verified',
        'https://oyishi.es/public/uploadfile/677fe54463e55.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=52',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_53',
        '53',
        'Maki gambas',
        'MAKI(8piezas)',
        '(gambas y aguacate...',
        NULL,
        4.5,
        '["Crustáceos"]',
        'verified',
        'https://oyishi.es/public/uploadfile/677fe54464251.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=53',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_54',
        '54',
        'Maki salmón con aguacate',
        'MAKI(8piezas)',
        '(arroz, salmón y ...',
        NULL,
        4.5,
        '["Frutos de cáscara"]',
        'verified',
        'https://oyishi.es/public/uploadfile/677fe544645e9.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=54',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_55',
        '55',
        'Maki atún con aguacate',
        'MAKI(8piezas)',
        '(arroz, atún y ag...',
        NULL,
        4.9,
        '["Frutos de cáscara"]',
        'verified',
        'https://oyishi.es/public/uploadfile/677fe5446490f.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=55',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_56',
        '56',
        'Maki surimi',
        'MAKI(8piezas)',
        '(surimi, aguacate ...',
        NULL,
        4,
        '["Crustáceos"]',
        'verified',
        'https://oyishi.es/public/uploadfile/677fe54fa4b24.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=56',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_57',
        '57',
        'Maki vegetal',
        'MAKI(8piezas)',
        '(aguacate y pepino...',
        NULL,
        3.5,
        '[]',
        'unknown',
        'https://oyishi.es/public/uploadfile/677fe54fa5167.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=57',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_58',
        '58',
        'Maki pez mantequilla',
        'MAKI(8piezas)',
        '(arroz y pez mante...',
        NULL,
        4.5,
        '["Frutos de cáscara"]',
        'verified',
        'https://oyishi.es/public/uploadfile/677fe54fa5574.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=58',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_59',
        '59',
        'Maki aguacate',
        'MAKI(8piezas)',
        '(arroz y aguacate)',
        NULL,
        3.5,
        '[]',
        'unknown',
        'https://oyishi.es/public/uploadfile/677fe54fa594d.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=59',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_60',
        '60',
        'Futomaki',
        'MAKI(8piezas)',
        '(relleno de salmó...',
        NULL,
        10.9,
        '["Crustáceos","Frutos de cáscara"]',
        'verified',
        'https://oyishi.es/public/uploadfile/677fe54fa5cab.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=60',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_61',
        '61',
        'Temaki de atún y  aguacate',
        'TEMAKI(1 piezas)',
        NULL,
        NULL,
        4.25,
        '[]',
        'unknown',
        'https://oyishi.es/public/uploadfile/677fe54fa5ffc.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=61',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_62',
        '62',
        'Temaki de salmón y aguacate',
        'TEMAKI(1 piezas)',
        NULL,
        NULL,
        4,
        '[]',
        'unknown',
        'https://oyishi.es/public/uploadfile/677fe54fa6310.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=62',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_63',
        '63',
        'Temaki California',
        'TEMAKI(1 piezas)',
        '(Gambas y aguacate...',
        NULL,
        4,
        '[]',
        'unknown',
        'https://oyishi.es/public/uploadfile/677fe54fa6571.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=63',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_64',
        '64',
        'Temaki de anguila',
        'TEMAKI(1 piezas)',
        NULL,
        NULL,
        4.65,
        '[]',
        'unknown',
        'https://oyishi.es/public/uploadfile/677fe54fa68e7.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=64',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_65',
        '65',
        'Temaki de pato',
        'TEMAKI(1 piezas)',
        NULL,
        NULL,
        4.5,
        '[]',
        'unknown',
        'https://oyishi.es/public/uploadfile/677fe55b49cc3.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=65',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_66',
        '66',
        'Temaki mantequilla',
        'TEMAKI(1 piezas)',
        NULL,
        NULL,
        4.5,
        '[]',
        'unknown',
        'https://oyishi.es/public/uploadfile/677fe55b4a1e0.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=66',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_67',
        '67',
        'Tartar salmón con aguacate',
        'EXLUSIVOS TARTAS',
        '(salmón y salsa...',
        NULL,
        12,
        '["Pescado","Frutos de cáscara"]',
        'verified',
        'https://oyishi.es/public/uploadfile/677fe55b4a642.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=67',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_68',
        '68',
        'Tartar atún con aguacate',
        'EXLUSIVOS TARTAS',
        'Atún aguante y sa...',
        NULL,
        12.5,
        '["Pescado","Frutos de cáscara"]',
        'verified',
        'https://oyishi.es/public/uploadfile/677fe55b4abdb.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=68',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_69',
        '69',
        'Yu-sen manguro',
        'EXLUSIVOS TARTAS',
        '(Atún poco picant...',
        NULL,
        13,
        '["Frutos de cáscara","Picante"]',
        'verified',
        'https://oyishi.es/public/uploadfile/677fe55b4b028.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=69',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_70',
        '70',
        'Tartar salmón',
        'EXLUSIVOS TARTAS',
        'Salmón y salsa',
        NULL,
        12,
        '["Pescado","Frutos de cáscara"]',
        'verified',
        'https://oyishi.es/public/uploadfile/677fe55b4b449.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=70',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_71',
        '71',
        'Sashimi salmón',
        'SASHIMI(9 cortes)',
        NULL,
        NULL,
        10.9,
        '["Frutos de cáscara"]',
        'verified',
        'https://oyishi.es/public/uploadfile/677fe55b4b848.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=71',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_72',
        '72',
        'Sashimi atún',
        'SASHIMI(9 cortes)',
        NULL,
        NULL,
        11.9,
        '["Frutos de cáscara"]',
        'verified',
        'https://oyishi.es/public/uploadfile/677fe55b4bbb9.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=72',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_73',
        '73',
        'Sashimi pez mantequilla',
        'SASHIMI(9 cortes)',
        NULL,
        NULL,
        10.9,
        '[]',
        'unknown',
        'https://oyishi.es/public/uploadfile/677fe55b4bf4f.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=73',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_74',
        '74',
        'Tataki maguro',
        'SASHIMI(9 cortes)',
        NULL,
        NULL,
        11.9,
        '["Frutos de cáscara"]',
        'verified',
        'https://oyishi.es/public/uploadfile/677fe56625568.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=74',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_75',
        '76',
        'Sashimi variado',
        'SASHIMI(9 cortes)',
        '(9 Cortes)',
        9,
        11,
        '["Frutos de cáscara"]',
        'verified',
        'https://oyishi.es/public/uploadfile/677fe56625b4a.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=75',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_76',
        NULL,
        'Sashimi variado (24 cortes)',
        'SASHIMI(9 cortes)',
        '(24 Cortes )',
        NULL,
        24,
        '["Frutos de cáscara"]',
        'verified',
        'https://oyishi.es/public/uploadfile/677fe56625eca.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=76',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_77',
        '77',
        'Kushiyaki salmón',
        'KUSHIYAKI(2 piezas)',
        'Salmón y salsa',
        NULL,
        6,
        '["Pescado","Frutos de cáscara"]',
        'verified',
        'https://oyishi.es/public/uploadfile/677fe566261c0.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=77',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_79',
        '79',
        'Kushiyaki gambas',
        'KUSHIYAKI(2 piezas)',
        'Gambas y salsa',
        NULL,
        4.9,
        '["Crustáceos","Pescado"]',
        'verified',
        'https://oyishi.es/public/uploadfile/677fe56626519.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=79',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_80',
        '80',
        'Yakitori brocheta de pollo',
        'KUSHIYAKI(2 piezas)',
        'Pollo puerros y sa...',
        NULL,
        4.5,
        '["Pescado","Sésamo"]',
        'verified',
        'https://oyishi.es/public/uploadfile/677fe56626888.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=80',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_81',
        '81',
        'Yakitori solomillo de buey',
        'KUSHIYAKI(2 piezas)',
        'Solomillo y salsa',
        NULL,
        5.9,
        '["Pescado"]',
        'verified',
        'https://oyishi.es/public/uploadfile/677fe56626b2e.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=81',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_82',
        '82',
        'Arroz de sushi',
        'PASTAS FRITAS Y PLANCHA',
        NULL,
        NULL,
        3,
        '[]',
        'unknown',
        'https://oyishi.es/public/uploadfile/677fe56626e02.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=82',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_83',
        '83',
        'Arroz blanco',
        'PASTAS FRITAS Y PLANCHA',
        NULL,
        NULL,
        2,
        '[]',
        'unknown',
        'https://oyishi.es/public/uploadfile/677fe5662711b.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=83',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_84',
        '84',
        'Yakisoba con gambas',
        'PASTAS FRITAS Y PLANCHA',
        '(yakisoba con gamb...',
        NULL,
        7.35,
        '["Crustáceos","Pescado"]',
        'verified',
        'https://oyishi.es/public/uploadfile/677fe56fec2d1.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=84',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_154',
        '84A',
        'yakisoba vegetal',
        'PASTAS FRITAS Y PLANCHA',
        '(yakisoba y verdur...',
        NULL,
        6.5,
        '["Gluten","Pescado"]',
        'verified',
        'https://oyishi.es/public/uploadfile/677fe56fec850.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=154',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_85',
        '85',
        'Yakiudon con gambas y  verduras',
        'PASTAS FRITAS Y PLANCHA',
        '(tallarines udon, ...',
        NULL,
        7.85,
        '["Crustáceos","Pescado"]',
        'verified',
        'https://oyishi.es/public/uploadfile/677fe56fecd71.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=85',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_86',
        '86',
        'Yakifideo con gambas y verduras',
        'PASTAS FRITAS Y PLANCHA',
        '(fideos, gambas y ...',
        NULL,
        7.85,
        '["Crustáceos","Pescado"]',
        'verified',
        'https://oyishi.es/public/uploadfile/677fe56fed1eb.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=86',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_87',
        '87',
        'Arroz con setas',
        'PASTAS FRITAS Y PLANCHA',
        '（Arroz seta huev...',
        NULL,
        7.25,
        '["Huevos","Pescado"]',
        'verified',
        'https://oyishi.es/public/uploadfile/677fe56fed589.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=87',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_88',
        '88',
        'Kaisen yakimeshi',
        'PASTAS FRITAS Y PLANCHA',
        '(Arroz frito con m...',
        NULL,
        8.25,
        '["Crustáceos","Huevos","Sésamo","Moluscos"]',
        'verified',
        'https://oyishi.es/public/uploadfile/677fe56fedaa2.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=88',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_89',
        '89',
        'Yakimeshi',
        'PASTAS FRITAS Y PLANCHA',
        '(Arroz frito con g...',
        NULL,
        6.95,
        '["Crustáceos","Huevos","Sésamo"]',
        'verified',
        'https://oyishi.es/public/uploadfile/677fe56fedf28.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=89',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_153',
        '89A',
        'Arroz frito con tres delicias',
        'PASTAS FRITAS Y PLANCHA',
        '(arroz, zanahoria,...',
        NULL,
        5.95,
        '["Huevos"]',
        'verified',
        'https://oyishi.es/public/uploadfile/677fe56fee2fe.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=153',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_128',
        '90',
        'Yakimeshi piña',
        'PASTAS FRITAS Y PLANCHA',
        '(Arroz frito con g...',
        NULL,
        7.5,
        '["Crustáceos","Huevos"]',
        'verified',
        'https://oyishi.es/public/uploadfile/677fe56fee779.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=128',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_90',
        '91',
        'Yakimeshi ternera',
        'PASTAS FRITAS Y PLANCHA',
        '(Arroz frito con t...',
        NULL,
        7.35,
        '["Huevos","Mostaza"]',
        'verified',
        'https://oyishi.es/public/uploadfile/677fe57b4df74.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=90',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_146',
        '91A',
        'Yakimeshi pollo',
        'PASTAS FRITAS Y PLANCHA',
        '(Arroz frito con p...',
        NULL,
        6.75,
        '["Huevos","Pescado"]',
        'verified',
        'https://oyishi.es/public/uploadfile/677fe57b4e6e1.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=146',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_91',
        '92',
        'Pollo teppanyaki',
        'PASTAS FRITAS Y PLANCHA',
        '(pechuga de pollo ...',
        NULL,
        9.45,
        '["Pescado","Soja"]',
        'verified',
        'https://oyishi.es/public/uploadfile/677fe57b4ebde.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=91',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_92',
        '93',
        'Ternera con setas',
        'PASTAS FRITAS Y PLANCHA',
        'Ternera y seta',
        NULL,
        8.5,
        '["Gluten","Pescado"]',
        'verified',
        'https://oyishi.es/public/uploadfile/677fe57b4f0f7.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=92',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_129',
        '94',
        'Ternera con verduras',
        'PASTAS FRITAS Y PLANCHA',
        'Ternera y verduras...',
        NULL,
        7.95,
        '["Gluten","Pescado"]',
        'verified',
        'https://oyishi.es/public/uploadfile/677fe57b4f5e5.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=129',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_93',
        '95',
        'Gambas con champiñones',
        'PASTAS FRITAS Y PLANCHA',
        'Gambas y champiño...',
        NULL,
        8.5,
        '["Crustáceos","Pescado"]',
        'verified',
        'https://oyishi.es/public/uploadfile/677fe57b4fa54.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=93',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_94',
        '96',
        'Ebi teppanyaki',
        'PASTAS FRITAS Y PLANCHA',
        '(gambas a la planc...',
        NULL,
        12.5,
        '["Crustáceos"]',
        'verified',
        'https://oyishi.es/public/uploadfile/677fe57b4fecc.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=94',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_95',
        '97',
        '1/2 pato crujiente con salsa agripicante',
        'PASTAS FRITAS Y PLANCHA',
        'Pato y salsa',
        NULL,
        11.5,
        '["Gluten","Pescado"]',
        'verified',
        'https://oyishi.es/public/uploadfile/677fe57b501e9.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=95',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_96',
        '98',
        'Pollo crujiente con  almendras',
        'PASTAS FRITAS Y PLANCHA',
        'pollo y almendras�...',
        NULL,
        7.45,
        '["Gluten","Soja"]',
        'verified',
        'https://oyishi.es/public/uploadfile/677fe57b5050c.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=96',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_97',
        '99',
        'Pollo crujiente al limón',
        'PASTAS FRITAS Y PLANCHA',
        'Pollo, pan ralland...',
        NULL,
        6.95,
        '["Gluten"]',
        'verified',
        'https://oyishi.es/public/uploadfile/677fe58873f80.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=97',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_98',
        '100',
        'Cerdo agridulce',
        'PASTAS FRITAS Y PLANCHA',
        'Carne de credo fri...',
        NULL,
        6.75,
        '["Gluten","Soja"]',
        'verified',
        'https://oyishi.es/public/uploadfile/677fe58874ec9.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=98',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_101',
        'F1',
        'Bandeja maki',
        'BANDEJAS Y COMBINADOS',
        '" 8maki salmon 8ma...',
        NULL,
        11.9,
        '["Frutos de cáscara"]',
        'verified',
        'https://oyishi.es/public/uploadfile/20250109163245916048.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=101',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_102',
        'F2',
        'Bandeja roll',
        'BANDEJAS Y COMBINADOS',
        '"8california roll ...',
        NULL,
        12.5,
        '["Crustáceos","Frutos de cáscara","Sésamo"]',
        'verified',
        'https://oyishi.es/public/uploadfile/20250109163256926463.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=102',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_103',
        'F3',
        'Bandeja omega',
        'BANDEJAS Y COMBINADOS',
        '"8 sésamo roll 8 ...',
        NULL,
        15.9,
        '["Frutos de cáscara"]',
        'verified',
        'https://oyishi.es/public/uploadfile/20250109163310388056.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=103',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_104',
        'F4',
        'Bandeja sushi',
        'BANDEJAS Y COMBINADOS',
        '" 4sushi salmon 4s...',
        NULL,
        11.5,
        '["Frutos de cáscara"]',
        'verified',
        'https://oyishi.es/public/uploadfile/20250109163321565815.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=104',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_105',
        'F5',
        'Bandeja sushi y maki',
        'BANDEJAS Y COMBINADOS',
        '" 8 maki salmon 2s...',
        NULL,
        13.9,
        '["Cacahuetes","Frutos de cáscara"]',
        'verified',
        'https://oyishi.es/public/uploadfile/20250109163331850922.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=105',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_106',
        'F12',
        'Bandeja',
        'BANDEJAS Y COMBINADOS',
        '" 4 maki salmon 4 ...',
        NULL,
        16.5,
        '[]',
        'unknown',
        'https://oyishi.es/public/uploadfile/20250109163339890158.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=106',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_159',
        'F12',
        'Bandeja',
        'BANDEJAS Y COMBINADOS',
        '(28 piezas)8 Spicy...',
        28,
        24.9,
        '["Pescado","Cacahuetes","Frutos de cáscara"]',
        'verified',
        'https://oyishi.es/public/uploadfile/20250114184136678941.jpg',
        'official',
        'https://oyishi.es/menu_detail.php?id=159',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_108',
        'F8',
        'Bandeja variada',
        'BANDEJAS Y COMBINADOS',
        '" 4 sushi pez ment...',
        NULL,
        29.5,
        '["Huevos","Pescado","Cacahuetes","Frutos de cáscara"]',
        'verified',
        'https://oyishi.es/public/uploadfile/20250109163348567061.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=108',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_109',
        'F12',
        'Bandeja',
        'BANDEJAS Y COMBINADOS',
        '" 4 sashimi salmon...',
        NULL,
        32.9,
        '["Gluten","Crustáceos","Frutos de cáscara","Sésamo"]',
        'verified',
        'https://oyishi.es/public/uploadfile/20250109163359942084.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=109',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_151',
        'F10',
        'Bandeja maki sushi sashimi',
        'BANDEJAS Y COMBINADOS',
        '8 maki salmon 8mak...',
        NULL,
        58.8,
        '["Cacahuetes","Frutos de cáscara","Sésamo"]',
        'verified',
        'https://oyishi.es/public/uploadfile/20250109163413587248.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=151',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_155',
        'F11',
        'Sushi Fusion',
        'BANDEJAS Y COMBINADOS',
        '2 Sushi atún flam...',
        NULL,
        18,
        '["Pescado","Frutos de cáscara"]',
        'verified',
        'https://oyishi.es/public/uploadfile/20250109163419236880.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=155',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_156',
        'F12',
        'Bandeja',
        'BANDEJAS Y COMBINADOS',
        '4 Aguacate uramaki...',
        NULL,
        21.9,
        '["Frutos de cáscara"]',
        'verified',
        'https://oyishi.es/public/uploadfile/20250109163428681401.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=156',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_157',
        'F13',
        'Bandeja Vegetariana',
        'BANDEJAS Y COMBINADOS',
        '4 Maki aguacate4 M...',
        NULL,
        13.95,
        '[]',
        'unknown',
        'https://oyishi.es/public/uploadfile/20250109163436454504.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=157',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_110',
        NULL,
        'Lata coca cola',
        'BEBIDA',
        NULL,
        NULL,
        2,
        '[]',
        'unknown',
        'https://oyishi.es/public/uploadfile/20250109163601371672.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=110',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_111',
        NULL,
        'Lata coca cola zero',
        'BEBIDA',
        NULL,
        NULL,
        2,
        '[]',
        'unknown',
        'https://oyishi.es/public/uploadfile/20250109163551250548.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=111',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_113',
        NULL,
        'Lata fanta naranja',
        'BEBIDA',
        NULL,
        NULL,
        2,
        '[]',
        'unknown',
        'https://oyishi.es/public/uploadfile/20250109163541268671.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=113',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_114',
        NULL,
        'Lata fanta limon',
        'BEBIDA',
        NULL,
        NULL,
        2,
        '[]',
        'unknown',
        'https://oyishi.es/public/uploadfile/20250109163534779175.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=114',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_115',
        NULL,
        'Lata nestea',
        'BEBIDA',
        NULL,
        NULL,
        2,
        '[]',
        'unknown',
        'https://oyishi.es/public/uploadfile/20250109163524977469.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=115',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_116',
        NULL,
        'Lata aquarius',
        'BEBIDA',
        NULL,
        NULL,
        2,
        '[]',
        'unknown',
        'https://oyishi.es/public/uploadfile/20250109163515327905.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=116',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_117',
        NULL,
        'Lata aquarius naranja',
        'BEBIDA',
        NULL,
        NULL,
        2,
        '[]',
        'unknown',
        'https://oyishi.es/public/uploadfile/20250109163507807371.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=117',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_118',
        NULL,
        'Agua',
        'BEBIDA',
        NULL,
        NULL,
        1.8,
        '[]',
        'unknown',
        'https://oyishi.es/public/uploadfile/20250109163459423062.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=118',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_119',
        NULL,
        'Lata cerveza',
        'BEBIDA',
        NULL,
        NULL,
        2,
        '[]',
        'unknown',
        'https://oyishi.es/public/uploadfile/20250109163452467929.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=119',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_123',
        NULL,
        'Vino de la casa',
        'VINO',
        NULL,
        NULL,
        6.5,
        '[]',
        'unknown',
        'https://oyishi.es/public/uploadfile/20250109163659121460.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=123',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_124',
        NULL,
        'Vino  tinto (La Rioja)',
        'VINO',
        NULL,
        NULL,
        11,
        '[]',
        'unknown',
        'https://oyishi.es/public/uploadfile/20250109163705233747.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=124',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_125',
        NULL,
        'Vino tinto (ribera del Duero)',
        'VINO',
        NULL,
        NULL,
        12,
        '[]',
        'unknown',
        'https://oyishi.es/public/uploadfile/20250109163711392981.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=125',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_126',
        NULL,
        'Vino rosado señorío llanos',
        'VINO',
        NULL,
        NULL,
        11,
        '[]',
        'unknown',
        'https://oyishi.es/public/uploadfile/20250109163726997220.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=126',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_127',
        NULL,
        'Vino blanco rueda',
        'VINO',
        NULL,
        NULL,
        11,
        '[]',
        'unknown',
        'https://oyishi.es/public/uploadfile/20250109163648428744.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=127',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_130',
        NULL,
        'Mochi sabor a soja rojo',
        'POSTRES',
        '(2p)',
        NULL,
        2.95,
        '[]',
        'unknown',
        'https://oyishi.es/public/images/no-imagen.jpg',
        'official',
        'https://oyishi.es/menu_detail.php?id=130',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_131',
        NULL,
        'Mochi sabor a cacahuete',
        'POSTRES',
        '(2p)',
        NULL,
        2.95,
        '[]',
        'unknown',
        'https://oyishi.es/public/images/no-imagen.jpg',
        'official',
        'https://oyishi.es/menu_detail.php?id=131',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_132',
        NULL,
        'Mochi sabor a sesamo',
        'POSTRES',
        '(2p)',
        NULL,
        2.95,
        '[]',
        'unknown',
        'https://oyishi.es/public/images/no-imagen.jpg',
        'official',
        'https://oyishi.es/menu_detail.php?id=132',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_133',
        NULL,
        'Movhi sabor de mango',
        'POSTRES',
        NULL,
        NULL,
        2.95,
        '[]',
        'unknown',
        'https://oyishi.es/public/images/no-imagen.jpg',
        'official',
        'https://oyishi.es/menu_detail.php?id=133',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_134',
        NULL,
        'Mochi sabor a taro',
        'POSTRES',
        '(2p)',
        NULL,
        2.95,
        '[]',
        'unknown',
        'https://oyishi.es/public/images/no-imagen.jpg',
        'official',
        'https://oyishi.es/menu_detail.php?id=134',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_141',
        NULL,
        'Tarta  de queso con arandanos',
        'POSTRES',
        NULL,
        NULL,
        2.9,
        '["Gluten","Cacahuetes"]',
        'verified',
        'https://oyishi.es/public/images/no-imagen.jpg',
        'official',
        'https://oyishi.es/menu_detail.php?id=141',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_145',
        NULL,
        'Tarta de tiramisu',
        'POSTRES',
        NULL,
        NULL,
        2.9,
        '["Gluten","Cacahuetes"]',
        'verified',
        'https://oyishi.es/public/images/no-imagen.jpg',
        'official',
        'https://oyishi.es/menu_detail.php?id=145',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_143',
        NULL,
        'tarta de san marcos',
        'POSTRES',
        NULL,
        NULL,
        2.9,
        '["Gluten","Cacahuetes"]',
        'verified',
        'https://oyishi.es/public/images/no-imagen.jpg',
        'official',
        'https://oyishi.es/menu_detail.php?id=143',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_144',
        NULL,
        'Tarta de selva de trufa',
        'POSTRES',
        NULL,
        NULL,
        2.9,
        '["Gluten","Cacahuetes"]',
        'verified',
        'https://oyishi.es/public/images/no-imagen.jpg',
        'official',
        'https://oyishi.es/menu_detail.php?id=144',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_135',
        NULL,
        'FORMULA 1',
        'MENU DIA',
        'De lunes a Viernes...',
        NULL,
        14.5,
        '["Soja","Frutos de cáscara"]',
        'verified',
        'https://oyishi.es/public/uploadfile/20250109163803978373.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=135',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_136',
        NULL,
        'FORMULA 2',
        'MENU DIA',
        '3 sushi salmon3 su...',
        NULL,
        14.5,
        '["Soja","Frutos de cáscara"]',
        'verified',
        'https://oyishi.es/public/uploadfile/20250109163810488373.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=136',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_137',
        NULL,
        'FORMULA 3',
        'MENU DIA',
        '4 sesamo roll4 mak...',
        NULL,
        14.5,
        '["Gluten","Pescado","Frutos de cáscara","Sésamo"]',
        'verified',
        'https://oyishi.es/public/uploadfile/20250109163817405004.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=137',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_138',
        NULL,
        'FORMULA 4',
        'MENU DIA',
        '3 sashimi salmon4 ...',
        NULL,
        14.5,
        '["Gluten","Frutos de cáscara"]',
        'verified',
        'https://oyishi.es/public/uploadfile/20250109163824923944.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=138',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_139',
        NULL,
        'FORMULA 5',
        'MENU DIA',
        '2 sashimi salmon4 ...',
        NULL,
        14.5,
        '["Frutos de cáscara"]',
        'verified',
        'https://oyishi.es/public/uploadfile/20250109163834479819.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=139',
        'oyishi.es',
        1,
        1
    );
INSERT OR REPLACE INTO products (id, reference, name, category, description, pieces, price, allergens, allergenStatus, imageUrl, imageStatus, sourceUrl, source, verified, active) VALUES (
        'p_140',
        NULL,
        'FORMULA 6',
        'MENU DIA',
        '2 Rollito gambas4 ...',
        NULL,
        14.5,
        '["Gluten","Pescado","Frutos de cáscara"]',
        'verified',
        'https://oyishi.es/public/uploadfile/20250109163841820807.png',
        'official',
        'https://oyishi.es/menu_detail.php?id=140',
        'oyishi.es',
        1,
        1
    );
